/*
 * generated by Xtext 2.17.0
 */
package org.xtext.imt.fil.dsl.ide


/**
 * Use this class to register ide components.
 */
class BrowserAutomationIdeModule extends AbstractBrowserAutomationIdeModule {
}
