/**
 * generated by Xtext 2.17.0
 */
package org.xtext.imt.fil.dsl.ide;

import org.xtext.imt.fil.dsl.ide.AbstractBrowserAutomationIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class BrowserAutomationIdeModule extends AbstractBrowserAutomationIdeModule {
}
