/**
 * generated by Xtext 2.17.0
 */
package org.xtext.imt.fil.dsl;

import org.xtext.imt.fil.dsl.AbstractBrowserAutomationRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class BrowserAutomationRuntimeModule extends AbstractBrowserAutomationRuntimeModule {
}
