/**
 * generated by Xtext 2.17.0
 */
package org.xtext.imt.fil.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.imt.fil.dsl.ui.AbstractBrowserAutomationUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BrowserAutomationUiModule extends AbstractBrowserAutomationUiModule {
  public BrowserAutomationUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
