/*
 * generated by Xtext 2.17.0
 */
package org.xtext.imt.fil.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class BrowserAutomationUiModule extends AbstractBrowserAutomationUiModule {
}
