/**
 * generated by Xtext 2.19.0
 */
package org.xtext.imt.fil.dsl.browserAutomation.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.imt.fil.dsl.browserAutomation.AttributeValue;
import org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage;
import org.xtext.imt.fil.dsl.browserAutomation.VarReference;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribute Value</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.imt.fil.dsl.browserAutomation.impl.AttributeValueImpl#getStringVal <em>String Val</em>}</li>
 *   <li>{@link org.xtext.imt.fil.dsl.browserAutomation.impl.AttributeValueImpl#getVarRefVal <em>Var Ref Val</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AttributeValueImpl extends MinimalEObjectImpl.Container implements AttributeValue
{
  /**
   * The default value of the '{@link #getStringVal() <em>String Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStringVal()
   * @generated
   * @ordered
   */
  protected static final String STRING_VAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStringVal() <em>String Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStringVal()
   * @generated
   * @ordered
   */
  protected String stringVal = STRING_VAL_EDEFAULT;

  /**
   * The cached value of the '{@link #getVarRefVal() <em>Var Ref Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarRefVal()
   * @generated
   * @ordered
   */
  protected VarReference varRefVal;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributeValueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BrowserAutomationPackage.Literals.ATTRIBUTE_VALUE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getStringVal()
  {
    return stringVal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStringVal(String newStringVal)
  {
    String oldStringVal = stringVal;
    stringVal = newStringVal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BrowserAutomationPackage.ATTRIBUTE_VALUE__STRING_VAL, oldStringVal, stringVal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VarReference getVarRefVal()
  {
    return varRefVal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVarRefVal(VarReference newVarRefVal, NotificationChain msgs)
  {
    VarReference oldVarRefVal = varRefVal;
    varRefVal = newVarRefVal;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BrowserAutomationPackage.ATTRIBUTE_VALUE__VAR_REF_VAL, oldVarRefVal, newVarRefVal);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarRefVal(VarReference newVarRefVal)
  {
    if (newVarRefVal != varRefVal)
    {
      NotificationChain msgs = null;
      if (varRefVal != null)
        msgs = ((InternalEObject)varRefVal).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BrowserAutomationPackage.ATTRIBUTE_VALUE__VAR_REF_VAL, null, msgs);
      if (newVarRefVal != null)
        msgs = ((InternalEObject)newVarRefVal).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BrowserAutomationPackage.ATTRIBUTE_VALUE__VAR_REF_VAL, null, msgs);
      msgs = basicSetVarRefVal(newVarRefVal, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BrowserAutomationPackage.ATTRIBUTE_VALUE__VAR_REF_VAL, newVarRefVal, newVarRefVal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BrowserAutomationPackage.ATTRIBUTE_VALUE__VAR_REF_VAL:
        return basicSetVarRefVal(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BrowserAutomationPackage.ATTRIBUTE_VALUE__STRING_VAL:
        return getStringVal();
      case BrowserAutomationPackage.ATTRIBUTE_VALUE__VAR_REF_VAL:
        return getVarRefVal();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BrowserAutomationPackage.ATTRIBUTE_VALUE__STRING_VAL:
        setStringVal((String)newValue);
        return;
      case BrowserAutomationPackage.ATTRIBUTE_VALUE__VAR_REF_VAL:
        setVarRefVal((VarReference)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BrowserAutomationPackage.ATTRIBUTE_VALUE__STRING_VAL:
        setStringVal(STRING_VAL_EDEFAULT);
        return;
      case BrowserAutomationPackage.ATTRIBUTE_VALUE__VAR_REF_VAL:
        setVarRefVal((VarReference)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BrowserAutomationPackage.ATTRIBUTE_VALUE__STRING_VAL:
        return STRING_VAL_EDEFAULT == null ? stringVal != null : !STRING_VAL_EDEFAULT.equals(stringVal);
      case BrowserAutomationPackage.ATTRIBUTE_VALUE__VAR_REF_VAL:
        return varRefVal != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (stringVal: ");
    result.append(stringVal);
    result.append(')');
    return result.toString();
  }

} //AttributeValueImpl
