/**
 * generated by Xtext 2.17.0
 */
package org.xtext.imt.fil.dsl.browserAutomation.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage;
import org.xtext.imt.fil.dsl.browserAutomation.VarReference;
import org.xtext.imt.fil.dsl.browserAutomation.Verify;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Verify</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.imt.fil.dsl.browserAutomation.impl.VerifyImpl#getVarToVerify <em>Var To Verify</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VerifyImpl extends ActionImpl implements Verify
{
  /**
   * The cached value of the '{@link #getVarToVerify() <em>Var To Verify</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarToVerify()
   * @generated
   * @ordered
   */
  protected VarReference varToVerify;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VerifyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BrowserAutomationPackage.Literals.VERIFY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VarReference getVarToVerify()
  {
    return varToVerify;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVarToVerify(VarReference newVarToVerify, NotificationChain msgs)
  {
    VarReference oldVarToVerify = varToVerify;
    varToVerify = newVarToVerify;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BrowserAutomationPackage.VERIFY__VAR_TO_VERIFY, oldVarToVerify, newVarToVerify);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarToVerify(VarReference newVarToVerify)
  {
    if (newVarToVerify != varToVerify)
    {
      NotificationChain msgs = null;
      if (varToVerify != null)
        msgs = ((InternalEObject)varToVerify).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BrowserAutomationPackage.VERIFY__VAR_TO_VERIFY, null, msgs);
      if (newVarToVerify != null)
        msgs = ((InternalEObject)newVarToVerify).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BrowserAutomationPackage.VERIFY__VAR_TO_VERIFY, null, msgs);
      msgs = basicSetVarToVerify(newVarToVerify, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BrowserAutomationPackage.VERIFY__VAR_TO_VERIFY, newVarToVerify, newVarToVerify));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BrowserAutomationPackage.VERIFY__VAR_TO_VERIFY:
        return basicSetVarToVerify(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BrowserAutomationPackage.VERIFY__VAR_TO_VERIFY:
        return getVarToVerify();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BrowserAutomationPackage.VERIFY__VAR_TO_VERIFY:
        setVarToVerify((VarReference)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BrowserAutomationPackage.VERIFY__VAR_TO_VERIFY:
        setVarToVerify((VarReference)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BrowserAutomationPackage.VERIFY__VAR_TO_VERIFY:
        return varToVerify != null;
    }
    return super.eIsSet(featureID);
  }

} //VerifyImpl
