/**
 * generated by Xtext 2.17.0
 */
package org.xtext.imt.fil.dsl.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.imt.fil.dsl.tests.BrowserAutomationInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(BrowserAutomationInjectorProvider.class)
@SuppressWarnings("all")
public class BrowserAutomationParsingTest {
  @Inject
  private /* ParseHelper<Test> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field BrowserAutomationParsingTest.parseHelper refers to the missing type Test"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
