/**
 * generated by Xtext 2.17.0
 */
package org.xtext.imt.fil.dsl.browserAutomation;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.imt.fil.dsl.browserAutomation.Action#getGet <em>Get</em>}</li>
 *   <li>{@link org.xtext.imt.fil.dsl.browserAutomation.Action#getVar <em>Var</em>}</li>
 * </ul>
 *
 * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Get</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Get</em>' containment reference.
   * @see #setGet(Get)
   * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getAction_Get()
   * @model containment="true"
   * @generated
   */
  Get getGet();

  /**
   * Sets the value of the '{@link org.xtext.imt.fil.dsl.browserAutomation.Action#getGet <em>Get</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Get</em>' containment reference.
   * @see #getGet()
   * @generated
   */
  void setGet(Get value);

  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(VarReference)
   * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getAction_Var()
   * @model containment="true"
   * @generated
   */
  VarReference getVar();

  /**
   * Sets the value of the '{@link org.xtext.imt.fil.dsl.browserAutomation.Action#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(VarReference value);

} // Action
