/**
 * generated by Xtext 2.17.0
 */
package org.xtext.imt.fil.dsl.browserAutomation;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.imt.fil.dsl.browserAutomation.AttributeValue#getStringVal <em>String Val</em>}</li>
 *   <li>{@link org.xtext.imt.fil.dsl.browserAutomation.AttributeValue#getVarRefVal <em>Var Ref Val</em>}</li>
 * </ul>
 *
 * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getAttributeValue()
 * @model
 * @generated
 */
public interface AttributeValue extends EObject
{
  /**
   * Returns the value of the '<em><b>String Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String Val</em>' attribute.
   * @see #setStringVal(String)
   * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getAttributeValue_StringVal()
   * @model
   * @generated
   */
  String getStringVal();

  /**
   * Sets the value of the '{@link org.xtext.imt.fil.dsl.browserAutomation.AttributeValue#getStringVal <em>String Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String Val</em>' attribute.
   * @see #getStringVal()
   * @generated
   */
  void setStringVal(String value);

  /**
   * Returns the value of the '<em><b>Var Ref Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Ref Val</em>' containment reference.
   * @see #setVarRefVal(VarReference)
   * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getAttributeValue_VarRefVal()
   * @model containment="true"
   * @generated
   */
  VarReference getVarRefVal();

  /**
   * Sets the value of the '{@link org.xtext.imt.fil.dsl.browserAutomation.AttributeValue#getVarRefVal <em>Var Ref Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Ref Val</em>' containment reference.
   * @see #getVarRefVal()
   * @generated
   */
  void setVarRefVal(VarReference value);

} // AttributeValue
