/**
 * generated by Xtext 2.17.0
 */
package org.xtext.imt.fil.dsl.browserAutomation;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationFactory
 * @model kind="package"
 * @generated
 */
public interface BrowserAutomationPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "browserAutomation";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/imt/fil/dsl/BrowserAutomation";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "browserAutomation";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BrowserAutomationPackage eINSTANCE = org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.TestImpl <em>Test</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.TestImpl
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getTest()
   * @generated
   */
  int TEST = 0;

  /**
   * The feature id for the '<em><b>Web Browser</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__WEB_BROWSER = 0;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__URL = 1;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__ACTIONS = 2;

  /**
   * The number of structural features of the '<em>Test</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.ActionImpl
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getAction()
   * @generated
   */
  int ACTION = 1;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.GetImpl <em>Get</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.GetImpl
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getGet()
   * @generated
   */
  int GET = 2;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET__VAR = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET__ELEMENT = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Attr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET__ATTR = ACTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Attr Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET__ATTR_VAL = ACTION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Get</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_FEATURE_COUNT = ACTION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.VariableImpl
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.VarReferenceImpl <em>Var Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.VarReferenceImpl
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getVarReference()
   * @generated
   */
  int VAR_REFERENCE = 4;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_REFERENCE__VAR = 0;

  /**
   * The number of structural features of the '<em>Var Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_REFERENCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.ClickImpl <em>Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.ClickImpl
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getClick()
   * @generated
   */
  int CLICK = 5;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__VAR = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.InsertImpl <em>Insert</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.InsertImpl
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getInsert()
   * @generated
   */
  int INSERT = 6;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__VALUE = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__VAR = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Insert</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.VerifyImpl <em>Verify</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.VerifyImpl
   * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getVerify()
   * @generated
   */
  int VERIFY = 7;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__VAR = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Verify</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.imt.fil.dsl.browserAutomation.Test <em>Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Test
   * @generated
   */
  EClass getTest();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.fil.dsl.browserAutomation.Test#getWebBrowser <em>Web Browser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Web Browser</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Test#getWebBrowser()
   * @see #getTest()
   * @generated
   */
  EAttribute getTest_WebBrowser();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.fil.dsl.browserAutomation.Test#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Test#getUrl()
   * @see #getTest()
   * @generated
   */
  EAttribute getTest_Url();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.imt.fil.dsl.browserAutomation.Test#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Test#getActions()
   * @see #getTest()
   * @generated
   */
  EReference getTest_Actions();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.fil.dsl.browserAutomation.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.fil.dsl.browserAutomation.Get <em>Get</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Get</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Get
   * @generated
   */
  EClass getGet();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.imt.fil.dsl.browserAutomation.Get#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Get#getVar()
   * @see #getGet()
   * @generated
   */
  EReference getGet_Var();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.fil.dsl.browserAutomation.Get#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Element</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Get#getElement()
   * @see #getGet()
   * @generated
   */
  EAttribute getGet_Element();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.fil.dsl.browserAutomation.Get#getAttr <em>Attr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attr</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Get#getAttr()
   * @see #getGet()
   * @generated
   */
  EAttribute getGet_Attr();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.fil.dsl.browserAutomation.Get#getAttrVal <em>Attr Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attr Val</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Get#getAttrVal()
   * @see #getGet()
   * @generated
   */
  EAttribute getGet_AttrVal();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.fil.dsl.browserAutomation.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.fil.dsl.browserAutomation.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.fil.dsl.browserAutomation.VarReference <em>Var Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Reference</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.VarReference
   * @generated
   */
  EClass getVarReference();

  /**
   * Returns the meta object for the reference '{@link org.xtext.imt.fil.dsl.browserAutomation.VarReference#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.VarReference#getVar()
   * @see #getVarReference()
   * @generated
   */
  EReference getVarReference_Var();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.fil.dsl.browserAutomation.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Click
   * @generated
   */
  EClass getClick();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.imt.fil.dsl.browserAutomation.Click#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Click#getVar()
   * @see #getClick()
   * @generated
   */
  EReference getClick_Var();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.fil.dsl.browserAutomation.Insert <em>Insert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Insert
   * @generated
   */
  EClass getInsert();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.imt.fil.dsl.browserAutomation.Insert#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Insert#getValue()
   * @see #getInsert()
   * @generated
   */
  EAttribute getInsert_Value();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.imt.fil.dsl.browserAutomation.Insert#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Insert#getVar()
   * @see #getInsert()
   * @generated
   */
  EReference getInsert_Var();

  /**
   * Returns the meta object for class '{@link org.xtext.imt.fil.dsl.browserAutomation.Verify <em>Verify</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Verify</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Verify
   * @generated
   */
  EClass getVerify();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.imt.fil.dsl.browserAutomation.Verify#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see org.xtext.imt.fil.dsl.browserAutomation.Verify#getVar()
   * @see #getVerify()
   * @generated
   */
  EReference getVerify_Var();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BrowserAutomationFactory getBrowserAutomationFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.TestImpl <em>Test</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.TestImpl
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getTest()
     * @generated
     */
    EClass TEST = eINSTANCE.getTest();

    /**
     * The meta object literal for the '<em><b>Web Browser</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST__WEB_BROWSER = eINSTANCE.getTest_WebBrowser();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST__URL = eINSTANCE.getTest_Url();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST__ACTIONS = eINSTANCE.getTest_Actions();

    /**
     * The meta object literal for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.ActionImpl
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.GetImpl <em>Get</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.GetImpl
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getGet()
     * @generated
     */
    EClass GET = eINSTANCE.getGet();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GET__VAR = eINSTANCE.getGet_Var();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GET__ELEMENT = eINSTANCE.getGet_Element();

    /**
     * The meta object literal for the '<em><b>Attr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GET__ATTR = eINSTANCE.getGet_Attr();

    /**
     * The meta object literal for the '<em><b>Attr Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GET__ATTR_VAL = eINSTANCE.getGet_AttrVal();

    /**
     * The meta object literal for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.VariableImpl
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.VarReferenceImpl <em>Var Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.VarReferenceImpl
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getVarReference()
     * @generated
     */
    EClass VAR_REFERENCE = eINSTANCE.getVarReference();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_REFERENCE__VAR = eINSTANCE.getVarReference_Var();

    /**
     * The meta object literal for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.ClickImpl <em>Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.ClickImpl
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getClick()
     * @generated
     */
    EClass CLICK = eINSTANCE.getClick();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLICK__VAR = eINSTANCE.getClick_Var();

    /**
     * The meta object literal for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.InsertImpl <em>Insert</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.InsertImpl
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getInsert()
     * @generated
     */
    EClass INSERT = eINSTANCE.getInsert();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT__VALUE = eINSTANCE.getInsert_Value();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__VAR = eINSTANCE.getInsert_Var();

    /**
     * The meta object literal for the '{@link org.xtext.imt.fil.dsl.browserAutomation.impl.VerifyImpl <em>Verify</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.VerifyImpl
     * @see org.xtext.imt.fil.dsl.browserAutomation.impl.BrowserAutomationPackageImpl#getVerify()
     * @generated
     */
    EClass VERIFY = eINSTANCE.getVerify();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERIFY__VAR = eINSTANCE.getVerify_Var();

  }

} //BrowserAutomationPackage
