/**
 * generated by Xtext 2.17.0
 */
package org.xtext.imt.fil.dsl.browserAutomation;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Check</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getCheck()
 * @model
 * @generated
 */
public interface Check extends Action
{
} // Check
