/**
 * generated by Xtext 2.17.0
 */
package org.xtext.imt.fil.dsl.browserAutomation;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Choose</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.imt.fil.dsl.browserAutomation.Choose#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.imt.fil.dsl.browserAutomation.Choose#getVarChoose <em>Var Choose</em>}</li>
 * </ul>
 *
 * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getChoose()
 * @model
 * @generated
 */
public interface Choose extends Action
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getChoose_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link org.xtext.imt.fil.dsl.browserAutomation.Choose#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Var Choose</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Choose</em>' containment reference.
   * @see #setVarChoose(VarReference)
   * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getChoose_VarChoose()
   * @model containment="true"
   * @generated
   */
  VarReference getVarChoose();

  /**
   * Sets the value of the '{@link org.xtext.imt.fil.dsl.browserAutomation.Choose#getVarChoose <em>Var Choose</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Choose</em>' containment reference.
   * @see #getVarChoose()
   * @generated
   */
  void setVarChoose(VarReference value);

} // Choose
