/**
 * generated by Xtext 2.19.0
 */
package org.xtext.imt.fil.dsl.browserAutomation;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Click</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.imt.fil.dsl.browserAutomation.Click#getVarClick <em>Var Click</em>}</li>
 * </ul>
 *
 * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getClick()
 * @model
 * @generated
 */
public interface Click extends Action
{
  /**
   * Returns the value of the '<em><b>Var Click</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Click</em>' containment reference.
   * @see #setVarClick(VarReference)
   * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getClick_VarClick()
   * @model containment="true"
   * @generated
   */
  VarReference getVarClick();

  /**
   * Sets the value of the '{@link org.xtext.imt.fil.dsl.browserAutomation.Click#getVarClick <em>Var Click</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Click</em>' containment reference.
   * @see #getVarClick()
   * @generated
   */
  void setVarClick(VarReference value);

} // Click
