/**
 * generated by Xtext 2.17.0
 */
package org.xtext.imt.fil.dsl.browserAutomation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.imt.fil.dsl.browserAutomation.Test#getWebBrowser <em>Web Browser</em>}</li>
 *   <li>{@link org.xtext.imt.fil.dsl.browserAutomation.Test#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getTest()
 * @model
 * @generated
 */
public interface Test extends EObject
{
  /**
   * Returns the value of the '<em><b>Web Browser</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Web Browser</em>' attribute.
   * @see #setWebBrowser(String)
   * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getTest_WebBrowser()
   * @model
   * @generated
   */
  String getWebBrowser();

  /**
   * Sets the value of the '{@link org.xtext.imt.fil.dsl.browserAutomation.Test#getWebBrowser <em>Web Browser</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Web Browser</em>' attribute.
   * @see #getWebBrowser()
   * @generated
   */
  void setWebBrowser(String value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.imt.fil.dsl.browserAutomation.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getTest_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

} // Test
