/**
 * generated by Xtext 2.19.0
 */
package org.xtext.imt.fil.dsl.browserAutomation;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verify</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.imt.fil.dsl.browserAutomation.Verify#getVarToVerify <em>Var To Verify</em>}</li>
 * </ul>
 *
 * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getVerify()
 * @model
 * @generated
 */
public interface Verify extends Action
{
  /**
   * Returns the value of the '<em><b>Var To Verify</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var To Verify</em>' containment reference.
   * @see #setVarToVerify(VarReference)
   * @see org.xtext.imt.fil.dsl.browserAutomation.BrowserAutomationPackage#getVerify_VarToVerify()
   * @model containment="true"
   * @generated
   */
  VarReference getVarToVerify();

  /**
   * Sets the value of the '{@link org.xtext.imt.fil.dsl.browserAutomation.Verify#getVarToVerify <em>Var To Verify</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var To Verify</em>' containment reference.
   * @see #getVarToVerify()
   * @generated
   */
  void setVarToVerify(VarReference value);

} // Verify
