/*
 * generated by Xtext 2.19.0
 */
package org.xtext.imt.fil.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BrowserAutomationAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/imt/fil/dsl/parser/antlr/internal/InternalBrowserAutomation.tokens");
	}
}
