/**
 * generated by Xtext 2.17.0
 */
package org.xtext.imt.fil.dsl.validation;

import org.xtext.imt.fil.dsl.validation.AbstractBrowserAutomationValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BrowserAutomationValidator extends AbstractBrowserAutomationValidator {
}
